### ISSUE TITLE
ArrayList Font Selection is not clickable in specific area

### ISSUE THREAD

**Issue by yKsenomorf** [yKsenomorf/Akrien-Issue-Tracker#11]
##### Make sure that you have checked for simillar features in **list_of_features.md** file, otherwise, we will add a "duplicate" label. 
1. Issue type (bug/request): bug
2. AntiLeak Platform (AAL/CL): CL
3. Name of the bug (e.g. CustomFont doesn't save @ startup): ArrayList Font Selection is not clickable in specific area
4. Detailed description (if needed: ArrayList font selection is clickable only in the middle of the form
5. Video, providing the bug (optional):
Clickable (hovering) : 
![383c8abf8c36d8b4239a718bf2bee10f44d75dc39f9ee8060aca007cb27b7ea7](https://user-images.githubusercontent.com/34306421/38465041-b4755118-3b1f-11e8-970a-f7668896e1f3.png)
NOT clickable (hovering)
![c9c4f24fd833b5b11a0dcc91fc7f159f6f44bd9a447ba3d1deaf055d44126e85](https://user-images.githubusercontent.com/34306421/38465047-cac741ec-3b1f-11e8-9dd6-7cde949544d6.png)
Hovering in different location
![693b94969e547fd330d9131b64b83842af9d0e9babe83ccafc743abcfa786df5](https://user-images.githubusercontent.com/34306421/38465076-3a81b170-3b20-11e8-8714-fb89c671ebd7.png)

**Comment by GayZakal** [comment]
жизненно.

**Comment by Fals3R** [comment]
Fixed
