### ISSUE TITLE
Добавь обратно

### ISSUE THREAD

**Issue by MrShevtsov2k** [yKsenomorf/Akrien-Issue-Tracker#21]
Before filling this form out, I'd like to confirm that I've readed the FAQ located at the #how-to-get-akrien channel and checked for the simillar errors

## General
Бупас рекуэст

＞ 

Верни обратно яв спид, питч спид, фастстеирс, сделай нормальное акб под аас, фастстеирс под 3.3.7, нормальный бупасс рефлекс ботов.

＞

**VIDEO/PICTURE**

＞
## Additional information
Ааль

＞

Билд 11

＞

**Comment by IgorFox01** [comment]
Согласен верни еблан сука
