### ISSUE TITLE
Akrien crash

### ISSUE THREAD

**Issue by Leneleshe** [yKsenomorf/Akrien-Issue-Tracker#26]
Before filling this form out, I'd like to confirm that I've readed the FAQ located at the #how-to-get-akrien channel and checked for the simillar errors

## General
**ISSUE TYPE**
Bug/feature request/bypass request

＞ Crash

**DESCRIPTION**

＞If I start AAL and choose akrien? he crash

**VIDEO/PICTURE**

＞ Crash
## Additional information
**AntiLeak platform** CL/AAL

＞ Windows?

**Modpack version**

＞ B 1337

**Comment by p0rnph03n1x** [comment]
For now you have to unpack "AkrienClient" on your C drive, otherwise it will crash
![explorer_2019-02-25_10-09-18](https://user-images.githubusercontent.com/12500332/53320054-78640d80-38e5-11e9-9b37-2cff2c881afe.png)
