### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by DerAllahEchte** [yKsenomorf/Akrien-Issue-Tracker#32]
## General
**Improvement TYPE**
Killaura, Cheststealer

**DESCRIPTION**
It would be nice if the killaura get a prediction. Th Cheststealer should get an autoclos opinion.

**Comment by Arthimo** [comment]
Хуесос хули ты это не закрываешь тут нету твоего темплейта  иди выпились сучка

**Comment by p0rnph03n1x** [comment]
`killaura get a prediction`
there is no need in this as separate option, killaura does that when you enable randomizations/disable quick rotations. It bypasses any anticheat.

**Comment by p0rnph03n1x** [comment]
ChestStealer autoclose will be implemented
