### ISSUE TITLE
HUD "Logo" parameters doesn't do anything

### ISSUE THREAD

**Issue by yKsenomorf** [yKsenomorf/Akrien-Issue-Tracker#9]
##### Make sure that you have checked for simillar features in **list_of_features.md** file, otherwise, we will add a "duplicate" label. 
1. Issue type (bug/request): bug
2. AntiLeak Platform (AAL/CL): CL
3. Name of the bug (e.g. CustomFont doesn't save @ startup): HUD "Logo" parameters doesn't do anything
4. Detailed description (if needed): (none) 
5. Video, providing the bug (optional): 
![71981cc58a83f7c34c7d22c14e8c17f0b9ba4d180842ef6ef49f59fb1284ad70](https://user-images.githubusercontent.com/34306421/38464957-7f073dda-3b1e-11e8-9565-c69e19796e36.png)

**Comment by Fals3R** [comment]
fixed
